version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-stretch
    steps:
      - checkout
      - run:
          name: Installing Ceedling
          command: gem install ceedling
      - run:
          name: Running Unit Tests
          command: ruby vendor\ceedling\bin\ceedling test:all
          
