version: 2.1
jobs:
  build:
    docker:
      # - image: circleci/ruby:2.6.5-stretch
      - image: circleci/python:3.7.6-stretch
    steps:
      - checkout
      - run:
          name: Install GCOVR
          command: pip install gcovr
      - run:
          name: Install Ruby
          command: sudo apt-get install ruby-full
      - run:
          name: Installing Ceedling
          command: sudo gem install ceedling
      - run:
          name: Running Unit Tests and Code Coverage
          command: ruby .ceedling/bin/ceedling gcov:all utils:gcov
